steps:
  - label: ":dynamic-buildkite: pipeline"
    command: "docker run -it ghcr.io/equinixmetal-buildkite/dynamic-buildkite-template:latest --trivy -help >pipeline.yml && docker run -it ghcr.io/equinixmetal-buildkite/dynamic-buildkite-template:latest --trivy >>pipeline.yml | buildkite-agent pipeline upload"
