steps:
  - command: echo "Checks out multiple git repositories"
    command: "wget https://github.com/equinixmetal-buildkite/dynamic-buildkite-template /releases/download/v1.1.0/dynamic-buildkite-template-v1.1.0-linux-amd64.tar.gz && tar -xzvf dynamic-buildkite-template-v1.1.0-linux-amd64.tar.gz && ./dynamic-buildkite-template | buildkite-agent pipeline upload"
